Fix NPE from AppOpsManager.checkPackage.
Since commit 0fcef84, any application can use below code
to insert an invalid op record:
    appOpsManager.checkPackage(0, null);

Use below command will see the invalid record breaks writeState.
  adb shell dumpsys appops write-settings

  Exception occurred while dumping:
  java.lang.NullPointerException: Attempt to invoke virtual method
  'boolean java.lang.String.equals(java.lang.Object)'
  on a null object reference
        at com.android.server.AppOpsService.writeState

And system server will crash in 30 minutes when saving the xml.

Change-Id: I6ebd24126f03bda048cc4070d24783887e4164f9